name: Debug Structure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Show root directory
      run: |
        echo "=== ROOT DIRECTORY ==="
        pwd
        ls -la
        
    - name: Show all folders
      run: |
        echo "=== ALL FOLDERS ==="
        find . -type d -name "*" | head -20
        
    - name: Look for package.json files
      run: |
        echo "=== PACKAGE.JSON FILES ==="
        find . -name "package.json" -type f
        
    - name: Check if frontend folder exists
      run: |
        echo "=== FRONTEND FOLDER CHECK ==="
        if [ -d "./frontend" ]; then
          echo "✅ Frontend folder EXISTS"
          ls -la ./frontend/
        else
          echo "❌ Frontend folder NOT FOUND"
        fi
        
    - name: Check backend folder
      run: |
        echo "=== BACKEND FOLDER CHECK ==="
        if [ -d "./backend" ]; then
          echo "✅ Backend folder EXISTS"
          ls -la ./backend/
        else
          echo "❌ Backend folder NOT FOUND"
        fi
